# Tugas 5 - Dataset messidor_features

In [22]:
from scipy.io import arff
import pandas as pd
import numpy as np

In [39]:
# one hot enconder
from sklearn.preprocessing import OneHotEncoder

# min max scaler to normalize
from sklearn.preprocessing import MinMaxScaler

# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split

In [40]:
col_names = []
for i in range(20):
    if i == 0:
        col_names.append('quality')
    if i == 1:
        col_names.append('prescreen')
    if i >= 2 and i <= 7:
        col_names.append('ma' + str(i))
    if i >= 8 and i <= 15:
        col_names.append('exudate' + str(i))
    if i == 16:
        col_names.append('euDist')
    if i == 17:
        col_names.append('diameter')
    if i == 18:
        col_names.append('amfm_class')
    if i == 19:
        col_names.append('label')
data = arff.loadarff('/content/drive/MyDrive/datamining/tugas/messidor_features.arff')
df = pd.DataFrame(data[0])

In [41]:
df.columns = [col_names]
df

quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class label  
0     0.486903  0.100025        1.0  b'0'  
1     0.520908  0.144414        0.0  b'0'  
2     0.530904  0.128548        0.0  b'1'  
3     0.483284  0.114790        0.0  b'0'  
4     0.475935  0.123572        0.0  b'1'  
...        ...       ...        ...   ...  
1146  0.537470  0.116795        0.0  b'0'  
1147  0.516733  0.124190        0.0  b'0'  
1148  0.560632  0.129843        0.0  b'0'  
1149  0.485972  0.106690        1.0  b'1'  
1150  0.556192  0.088957        0.0  b'0'  

[1151 rows x 20 columns]

In [43]:
X = df.drop(columns=['label'])
X

quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class  
0     0.486903  0.100025        1.0  
1     0.520908  0.144414        0.0  
2     0.530904  0.128548        0.0  
3     0.483284  0.114790        0.0  
4     0.475935  0.123572        0.0  
...        ...       ...        ...  
1146  0.537470  0.116795        0.0  
1147  0.516733  0.124190        0.0  
1148  0.560632  0.129843        0.0  
1149  0.485972  0.106690        1.0  
1150  0.556192  0.088957        0.0  

[1151 rows x 19 columns]

# Normalisasi
## Normalisasi Min - Max
$$ x'=\frac{x-x_{min}}{x_{max}-x_{min}}$$  


In [44]:
from sklearn.preprocessing import MinMaxScaler

import joblib
scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(X)
features_names = X.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features.head(10)
# scaler_filename = "scaled.save" #normalisasi di save digunakan testing
# joblib.dump(scaler, scaler_filename) 
# scaler = joblib.load(scaler_filename)

quality prescreen       ma2       ma3       ma4       ma5       ma6  \
0     1.0       1.0  0.140000  0.160305  0.176471  0.173077  0.177083   
1     1.0       1.0  0.153333  0.175573  0.176471  0.163462  0.156250   
2     1.0       1.0  0.406667  0.450382  0.487395  0.509615  0.479167   
3     1.0       1.0  0.360000  0.396947  0.436975  0.471154  0.437500   
4     1.0       1.0  0.286667  0.328244  0.361345  0.384615  0.395833   
5     1.0       1.0  0.286667  0.320611  0.336134  0.384615  0.375000   
6     1.0       0.0  0.186667  0.213740  0.235294  0.250000  0.250000   
7     1.0       1.0  0.033333  0.038168  0.042017  0.048077  0.010417   
8     1.0       1.0  0.140000  0.152672  0.142857  0.134615  0.125000   
9     1.0       1.0  0.520000  0.564885  0.605042  0.673077  0.656250   

        ma7  exudate8  exudate9 exudate10 exudate11 exudate12 exudate13  \
0  0.147727  0.122764  0.106359  0.049693  0.012913  0.000362  0.000342   
1  0.136364  0.142126  0.142403  0.031351  0.003918  0.000076  0.000194   
2  0.363636  0.137472  0.167497  0.119614  0.081188  0.027106  0.018571   
3  0.340909  0.099403  0.110368  0.085971  0.051525  0.016340  0.013555   
4  0.295455  0.043799  0.051281  0.003869  0.000000  0.000000  0.000000   
5  0.318182  0.069395  0.041498  0.021738  0.005417  0.000000  0.000000   
6  0.170455  0.037412  0.054531  0.015400  0.000000  0.000000  0.000000   
7  0.000000  0.050374  0.056828  0.011536  0.002516  0.000000  0.000000   
8  0.102273  0.164381  0.140880  0.057991  0.008305  0.000000  0.000000   
9  0.522727  0.053997  0.060159  0.008246  0.001670  0.000455  0.000000   

  exudate14 exudate15    euDist  diameter amfm_class  
0  0.000661  0.001271  0.530801  0.261133        1.0  
1  0.000657  0.001264  0.682302  0.536341        0.0  
2  0.007043  0.002509  0.726836  0.437973        0.0  
3  0.001289  0.000496  0.514678  0.352675        0.0  
4  0.000000  0.000000  0.481936  0.407122        0.0  
5  0.000000  0.000000  0.601764  0.426770        0.0  
6  0.000000  0.000000  0.775126  0.506339        0.0  
7  0.000000  0.000000  0.929166  0.081622        1.0  
8  0.000000  0.000000  0.589477  0.365093        0.0  
9  0.000000  0.000000  0.860738  0.317608        0.0

In [45]:
testdates = arff.loadarff('/content/drive/MyDrive/datamining/tugas/messidor_features.arff')

In [46]:
y = df['label'].values
y[0:5]

array([[b'0'],
       [b'0'],
       [b'1'],
       [b'0'],
       [b'1']], dtype=object)

In [47]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [48]:
ybaru = le.transform(y)

In [49]:
ybaru

array([0, 0, 1, ..., 0, 1, 0])

Pembagian data test mempengaruhi akurasi

# **Modelling**

**Model Gaussian Naive Bayes**

In [50]:
# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

#train = data latih & test = data uji
#train_size dan test_size jika di jumlah harus = 1
training, test = train_test_split(scaled, train_size = 0.8, test_size = 0.2, shuffle=False)
training_label, test_label = train_test_split(ybaru, train_size = 0.8, test_size = 0.2, shuffle=False)

clf2 = GaussianNB()
clf2.fit(training, training_label)

probas = clf2.predict_proba(test)
probas = probas[:,1]
probas.shape

probas

test_label

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [51]:
probas = probas.round()
probas

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1.

In [63]:
# classifier
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()

gaussian.fit(training, training_label)
Y_pred = gaussian.predict(test) 
accuracy_nb=round(accuracy_score(test_label,probas)* 100, 2)
acc_gaussian = round(gaussian.score(training, training_label) * 100, 2)

cm = confusion_matrix(test_label, probas)
accuracy = accuracy_score(test_label,probas)
precision =precision_score(test_label, probas,average='micro')
recall =  recall_score(test_label, probas,average='micro')
f1 = f1_score(test_label,probas,average='micro')
print('Confusion matrix for Gaussian Naive Bayes\n',cm)
print('accuracy_Gaussian Naive Bayes: %.3f' %accuracy)
print('precision_Gaussian Naive Bayes: %.3f' %precision)
print('recall_Gaussian Naive Bayes: %.3f' %recall)
print('f1-score_random_Forest : %.3f' %f1)

Confusion matrix for Gaussian Naive Bayes
 [[65 50]
 [34 82]]
accuracy_Gaussian Naive Bayes: 0.636
precision_Gaussian Naive Bayes: 0.636
recall_Gaussian Naive Bayes: 0.636
f1-score_random_Forest : 0.636


In [53]:
#data latih / training
print('Data Training : ',training.shape)
print('Data Testing : ',test.shape)

Data Training :  (920, 19)
Data Testing :  (231, 19)


**Model K-NN**

In [71]:
amount_of_neighbor=10

In [72]:
# classifier
knn = KNeighborsClassifier(amount_of_neighbor)

knn.fit(training, training_label)
Y_pred = knn.predict(test) 
accuracy_nb=round(accuracy_score(test_label,probas)* 100, 2)
acc_knn = round(knn.score(training, training_label) * 100, 2)

cm = confusion_matrix(test_label, probas)
accuracy = accuracy_score(test_label,probas)
precision =precision_score(test_label, probas,average='micro')
recall =  recall_score(test_label, probas,average='micro')
f1 = f1_score(test_label,probas,average='micro')
print('Confusion matrix for Knn\n',cm)
print('accuracy_Knn: %.3f' %accuracy)
print('precision_Knn: %.3f' %precision)
print('recall_Knn: %.3f' %recall)
print('f1-score_random_Forest : %.3f' %f1)

Confusion matrix for Knn
 [[65 50]
 [34 82]]
accuracy_Knn: 0.636
precision_Knn: 0.636
recall_Knn: 0.636
f1-score_random_Forest : 0.636
