# Tugas 5 - Dataset messidor_features

In [ ]:
from scipy.io import arff
import pandas as pd
import numpy as np
from scipy.io.arff import loadarff 
from io import StringIO, BytesIO
import urllib.request

In [ ]:
col_names = []
for i in range(20):
    if i == 0:
        col_names.append('quality')
    if i == 1:
        col_names.append('prescreen')
    if i >= 2 and i <= 7:
        col_names.append('ma' + str(i))
    if i >= 8 and i <= 15:
        col_names.append('exudate' + str(i))
    if i == 16:
        col_names.append('euDist')
    if i == 17:
        col_names.append('diameter')
    if i == 18:
        col_names.append('amfm_class')
    if i == 19:
        col_names.append('label')
data = arff.loadarff('/content/drive/MyDrive/datamining/tugas/messidor_features.arff')
df = pd.DataFrame(data[0])

In [ ]:
df.columns = [col_names]
df

quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class label  
0     0.486903  0.100025        1.0  b'0'  
1     0.520908  0.144414        0.0  b'0'  
2     0.530904  0.128548        0.0  b'1'  
3     0.483284  0.114790        0.0  b'0'  
4     0.475935  0.123572        0.0  b'1'  
...        ...       ...        ...   ...  
1146  0.537470  0.116795        0.0  b'0'  
1147  0.516733  0.124190        0.0  b'0'  
1148  0.560632  0.129843        0.0  b'0'  
1149  0.485972  0.106690        1.0  b'1'  
1150  0.556192  0.088957        0.0  b'0'  

[1151 rows x 20 columns]

In [ ]:
X = df.drop(columns=['label'])
X

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:4150: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class  
0     0.486903  0.100025        1.0  
1     0.520908  0.144414        0.0  
2     0.530904  0.128548        0.0  
3     0.483284  0.114790        0.0  
4     0.475935  0.123572        0.0  
...        ...       ...        ...  
1146  0.537470  0.116795        0.0  
1147  0.516733  0.124190        0.0  
1148  0.560632  0.129843        0.0  
1149  0.485972  0.106690        1.0  
1150  0.556192  0.088957        0.0  

[1151 rows x 19 columns]

# Normalisasi
## Normalisasi Min - Max
$$ x'=\frac{x-x_{min}}{x_{max}-x_{min}}$$  


In [ ]:
from sklearn.preprocessing import MinMaxScaler

import joblib
scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(X)
features_names = X.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features.head(10)
#menyimpan min max untuk testing
scaler_filename = "scaled.save"
joblib.dump(scaler, scaler_filename) 
scaler = joblib.load(scaler_filename)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


In [ ]:
scaled

array([[1.        , 1.        , 0.14      , ..., 0.53080127, 0.26113347,
        1.        ],
       [1.        , 1.        , 0.15333333, ..., 0.68230157, 0.5363407 ,
        0.        ],
       [1.        , 1.        , 0.40666667, ..., 0.72683611, 0.43797313,
        0.        ],
       ...,
       [1.        , 0.        , 0.32      , ..., 0.85928137, 0.446002  ,
        0.        ],
       [1.        , 1.        , 0.25333333, ..., 0.52665345, 0.30245578,
        1.        ],
       [1.        , 1.        , 0.04      , ..., 0.83950012, 0.192513  ,
        0.        ]])

In [ ]:
features_names

MultiIndex([(   'quality',),
            ( 'prescreen',),
            (       'ma2',),
            (       'ma3',),
            (       'ma4',),
            (       'ma5',),
            (       'ma6',),
            (       'ma7',),
            (  'exudate8',),
            (  'exudate9',),
            ( 'exudate10',),
            ( 'exudate11',),
            ( 'exudate12',),
            ( 'exudate13',),
            ( 'exudate14',),
            ( 'exudate15',),
            (    'euDist',),
            (  'diameter',),
            ('amfm_class',)],
           )

In [ ]:
y = df['label'].values
y[0:5]

array([[b'0'],
       [b'0'],
       [b'1'],
       [b'0'],
       [b'1']], dtype=object)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [ ]:
ybaru = le.transform(y)
ybaru

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 1, ..., 0, 1, 0])

Modelling

**Model Gaussian Naive Bayes**

In [ ]:
# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

training, test = train_test_split(scaled, train_size = 0.8, test_size = 0.2, shuffle=False)
training_label, test_label = train_test_split(ybaru, train_size = 0.8, test_size = 0.2, shuffle=False)

clf2 = GaussianNB()
clf2.fit(training, training_label)

probas = clf2.predict_proba(test)
probas = probas[:,1]
probas.shape

(231,)

In [ ]:
test_label

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
probas

array([0.75620474, 0.11189161, 1.        , 0.10486252, 0.14252695,
       1.        , 0.87186459, 0.08938164, 0.06195771, 0.07016774,
       1.        , 0.07309769, 0.99377827, 0.08398282, 0.99999961,
       0.85347824, 0.91850879, 0.07858852, 0.64476537, 0.21435453,
       0.09334844, 0.9769378 , 0.95011339, 0.68211181, 0.96900188,
       0.99890913, 0.99724613, 0.16434853, 0.86018358, 0.99999363,
       0.53634466, 0.08895374, 0.98313892, 0.29158109, 0.25465845,
       1.        , 0.42762289, 0.88627287, 0.48478246, 0.68057536,
       0.09285228, 0.92485924, 0.12602622, 0.99996256, 0.67208144,
       0.95535994, 0.08212779, 0.92138625, 0.14110054, 0.29346465,
       0.99957587, 0.09783595, 0.07974339, 0.63233074, 0.2814182 ,
       1.        , 0.14248748, 1.        , 1.        , 0.99977481,
       0.94905966, 0.32335402, 0.66732001, 0.98470723, 0.99924866,
       0.91560627, 0.09860317, 0.99956381, 0.13165869, 0.93304628,
       1.        , 0.1097288 , 0.336975  , 0.67880805, 0.07551

In [ ]:
probas = probas.round()

probas

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1.

In [ ]:
Evaluasi

In [ ]:
accuracy_score(test_label, probas)

0.6363636363636364